### ISSUE TITLE
Error: ALL_BUILD project failed to build

### ISSUE THREAD

**Issue by DarkNemesis** [dragonCASTjosh/Clockwork#1]
After building the ALL_BUILD project, the results are:

Build: 65 succeeded, 2 failed, 0 up-to-date, 0 skipped
>F:\Clockwork\build\bin\28_Clockwork2DPhysicsRope_d.exe : fatal error LNK1169: one or more multiply defined symbols found
>F:\Clockwork\build\bin\36_Clockwork2DTileMap_d.exe : fatal error LNK1169: one or more multiply defined symbols found

**Comment by dragonCASTjosh** [comment]
should be fixed in newest version
