### ISSUE TITLE
Urho3D license missing?

### ISSUE THREAD

**Issue by cadaver** [dragonCASTjosh/Clockwork#2]
Hi,
it seems you have taken the Urho3D source code and replaced the license with your own, with the original Urho3D license nowhere to be seen? Apologies in case it is somewhere, but at least a cursory look didn't reveal it. If it's not included anywhere, it would be a violation of Urho3D's MIT license.

**Comment by dragonCASTjosh** [comment]
If im honest this repo wasnt event ment to be public yet, but ill be sure to include it with the next commit , sorry for missing that and thank you for letting me know i never intend to violate any licences

**Comment by dragonCASTjosh** [comment]
Should be fixed now, i added the Urho3D Licence and thanks for a strong Engine that me and my team and use as a Core :)

**Comment by cadaver** [comment]
Thanks for the addition. I probably wouldn't have noticed this repository if it wasn't for your Urho3D pull request :)
